name: Continuous Integration

on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

jobs:
    Build:
        name: Building
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v3
            - name: Use Node.js v16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Use pnpm v6
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 6.30.0
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Build project
              run: pnpm build

    Lint:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v3
            - name: Use Node.js v16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Use pnpm v6
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 6.30.0
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Build project
              run: pnpm build
            - name: Run ESLint
              run: pnpm lint --fix=false

    Test:
        name: Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v3
            - name: Use Node.js v16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Use pnpm v6
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 6.30.0
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Build project
              run: pnpm build
            - name: Run tests
              run: pnpm test
